### ISSUE TITLE
我有几个疑问求解答

### ISSUE THREAD

**Issue by pigvip2015** [zhihu-huawei251/zhihu-huawei251#12]
1.举报没有实质性证据，为啥不会以同样得方式关押举报人251天。
2.受害人没要公开道歉，要得赔偿。（自己的后路都没有了，为啥不要求公开道歉）

**Comment by OmmyZhang** [comment]
1. 因为那里是深圳龙岗，不然你以为为什么没证据就可以抓人还每个环节全部顶格拖时间
2. 赔偿是按规定给的，不是要的。“最大的诉求是希望华为跟自己道歉”

非技术问题不建议在github讨论
