### ISSUE TITLE
靠，我让永久禁言了

### ISSUE THREAD

**Issue by tzf1003** [zhihu-huawei251/zhihu-huawei251#3]
怎么办

**Comment by OmmyZhang** [comment]
惨啊。。（你是不是没开匿名

**Comment by tzf1003** [comment]
开匿名了，发了不到十条，就凉了

**Comment by meigancaishaobing** [comment]
网络世界还相信匿名这东西？

**Comment by tzf1003** [comment]
我太难了

**Comment by OmmyZhang** [comment]
@LichKing69 主要是我之前匿名的时候搞出了十页违规记录什么惩罚都没有，不匿名刷了一次就封号了
我怀疑可能是知乎普通管理员只能看到匿名用户背后是谁，但是看不到某个用户匿名发过哪些东西，所以只能按单次的处理

**Comment by OmmyZhang** [comment]
好像是知乎的反作弊系统更新了。。
