### ISSUE TITLE
匿名警告 - A(false) 也会以实名发布内容

### ISSUE THREAD

**Issue by bofeiw** [zhihu-huawei251/zhihu-huawei251#6]
测试了两波，都是使用了A(false)。
第二次手动把script里的变量hard code成了false，
结果还是实名状态发布了一堆回答。

-- 距离第一次发布4个实名回答4个小时后，知乎进行了折叠处理，原因为不符合问题的限定范围，但暂时还没被封号

**Comment by OmmyZhang** [comment]
其实A(true)或者A()是匿名，A(false)是不匿名
