### ISSUE TITLE
建议将逻辑修改为：在已有回答后加入后缀

### ISSUE THREAD

**Issue by Yesterday17** [zhihu-huawei251/zhihu-huawei251#7]
怎么说新发布无关回答都有点太极端了（虽然这事本身就...）
修改原有回答相对会好一些（也好不到哪里去，毕竟 #5 #6

**Comment by OmmyZhang** [comment]
有道理 正好可以和 #1 结合起来，做成自动加后缀的油猴脚本

**Comment by OmmyZhang** [comment]
已完成自动加后缀脚本
因为本人的号已经被封了需要回答较多的号协助测试，看需不需要改进频率、文字等
